/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Compaq
 */
public class CreateAttendance extends javax.swing.JFrame {

    /**
     * Creates new form CreateAttendance
     */
    public CreateAttendance() {
        initComponents();
       this.setLocationRelativeTo(null);
       jComboBox1.setSelectedItem(null);
       jComboBox2.setSelectedItem(null);
       getContentPane().setBackground(Color.LIGHT_GRAY);
    }

    PreparedStatement pst = null;
    Connection conn = null;
    ResultSet rs = null;
    
    public void fillcombobox(){
        try
        {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        String sql = "select * from subject where semester =? and branch =?";
        
        try{
            
           PreparedStatement pst =  conn.prepareStatement(sql);
           pst.setString(1,(String)(jComboBox1.getSelectedItem()));
           pst.setString(2,(String)(jComboBox2.getSelectedItem()));
           rs =  pst.executeQuery();
            while(rs.next())
            {
                String sub = rs.getString("subjectname");
                jComboBox11.addItem(sub);
                jComboBox55.addItem(sub);
                jComboBox22.addItem(sub);
                jComboBox44.addItem(sub);
                jComboBox33.addItem(sub);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox33 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jComboBox44 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox();
        jComboBox55 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Attendance");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        l3.setText("subject3");

        l1.setText("subject1");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox33.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox33.setMinimumSize(new java.awt.Dimension(30, 20));
        jComboBox33.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboBox33.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox33PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox44.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox44.setMinimumSize(new java.awt.Dimension(30, 20));
        jComboBox44.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboBox44.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox44PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        jComboBox22.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox22.setMinimumSize(new java.awt.Dimension(30, 20));
        jComboBox22.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboBox22.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox22PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox22ActionPerformed(evt);
            }
        });

        jComboBox55.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox55.setMinimumSize(new java.awt.Dimension(30, 20));
        jComboBox55.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboBox55.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox55PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jComboBox11.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox11.setMinimumSize(new java.awt.Dimension(30, 20));
        jComboBox11.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboBox11.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox11PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Semester");

        l5.setText("subject5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Student Attendance");

        l4.setText("subject4");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Roll No.");

        l2.setText("subject2");

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Branch");

        jComboBox2.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPUTER", "MECH", "CIVIL", "ELECTRICAL", "ETC", "EEE", "E&I" }));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Get Subjects");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l3)
                .addGap(114, 114, 114)
                .addComponent(l4)
                .addGap(97, 97, 97)
                .addComponent(l5)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(l1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jComboBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton3)
                                .addGap(27, 27, 27)
                                .addComponent(jButton4)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jComboBox55, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox44, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(l4)
                    .addComponent(l3)
                    .addComponent(l2)
                    .addComponent(l1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String msg ="";
                new EmployeeHomePage().setVisible(true);
            }
        });
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox33PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox33PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String tmp = (String)jComboBox33.getSelectedItem();
        String sql = "select * from subject where subjectname = ? and semester = ? and branch =?";

        try{

            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2,(String)(jComboBox1.getSelectedItem()));
           pst.setString(3,(String)(jComboBox2.getSelectedItem()));
            rs = pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("subjectid");
                l3.setText(id);
            }
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jComboBox33PopupMenuWillBecomeInvisible

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox44PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox44PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String tmp = (String)jComboBox44.getSelectedItem();
        String sql = "select * from subject where subjectname = ? and semester = ? and branch = ?";

        try{

            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2,(String)(jComboBox1.getSelectedItem()));
           pst.setString(3,(String)(jComboBox2.getSelectedItem()));
            rs =  pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("subjectid");
                l4.setText(id);
            }
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jComboBox44PopupMenuWillBecomeInvisible

    private void jComboBox22PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox22PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String tmp = (String)jComboBox22.getSelectedItem();
        String sql = "select * from subject where subjectname = ? and semester = ? and branch =?";

        try{

            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2,(String)(jComboBox1.getSelectedItem()));
           pst.setString(3,(String)(jComboBox2.getSelectedItem()));
            rs = pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("subjectid");
                l2.setText(id);
            }
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jComboBox22PopupMenuWillBecomeInvisible

    private void jComboBox55PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox55PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String tmp = (String)jComboBox55.getSelectedItem();
        String sql = "select * from subject where subjectname = ? and semester = ? and branch = ?";

        try{

            pst =  conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2,(String)(jComboBox1.getSelectedItem()));
           pst.setString(3,(String)(jComboBox2.getSelectedItem()));
            rs =  pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("subjectid");
                l5.setText(id);
            }
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jComboBox55PopupMenuWillBecomeInvisible

    private void jComboBox11PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox11PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String tmp = (String)jComboBox11.getSelectedItem();
        String sql = "select * from subject where subjectname = ? and semester = ? and branch = ?";

        try{

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2,(String)(jComboBox1.getSelectedItem()));
           pst.setString(3,(String)(jComboBox2.getSelectedItem()));
            rs = pst.executeQuery();
            if(rs.next())
            {
                String id = rs.getString("subjectid");
                l1.setText(id);
            }
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jComboBox11PopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
            String sql = "insert into student (idstudent,studentname, dept,semester, subject_subjectid) values(?,?,?,?,?)";
            pst =  conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            pst.setString(2, jTextField1.getText());
            pst.setString(4,(String)jComboBox1.getSelectedItem());
            pst.setString(3,(String)jComboBox2.getSelectedItem());
            pst.setString(5,l1.getText());
            // System.out.println(l1.getText());
            pst.execute();
            //JOptionPane.showMessageDialog(null, "Saved");

        } catch (Exception e ) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
            String sql = "insert into student (idstudent,studentname, dept,semester, subject_subjectid) values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            pst.setString(2, jTextField1.getText());
            pst.setString(4,(String)jComboBox1.getSelectedItem());
            pst.setString(3,(String)jComboBox2.getSelectedItem());
            pst.setString(5,l2.getText());
            //System.out.println(l1.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (Exception e ) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, e);
        }

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
            String sql = "insert into student (idstudent,studentname, dept,semester, subject_subjectid) values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            pst.setString(2, jTextField1.getText());
             pst.setString(4,(String)jComboBox1.getSelectedItem());
            pst.setString(3,(String)jComboBox2.getSelectedItem());
            pst.setString(5,l3.getText());
            //System.out.println(l1.getText());
            pst.execute();
            //JOptionPane.showMessageDialog(null, "Saved");

        } catch (Exception e ) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, e);
        }

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
            String sql = "insert into student (idstudent,studentname, dept,semester, subject_subjectid) values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            pst.setString(2, jTextField1.getText());
            pst.setString(4,(String)jComboBox1.getSelectedItem());
            pst.setString(3,(String)jComboBox2.getSelectedItem());
            pst.setString(5,l4.getText());
            //System.out.println(l1.getText());
            pst.execute();
            //JOptionPane.showMessageDialog(null, "Saved");

        } catch (Exception e ) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, e);
        }

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
            String sql = "insert into student (idstudent,studentname, dept,semester, subject_subjectid) values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            pst.setString(2, jTextField1.getText());
            pst.setString(4,(String)jComboBox1.getSelectedItem());
            pst.setString(3,(String)jComboBox2.getSelectedItem());
            pst.setString(5,l5.getText());
            //System.out.println(l1.getText());
            int ps = pst.executeUpdate();
            if(ps>0)
            {
                JOptionPane.showMessageDialog(null,"Attendance created successfully");
            }

        } catch (Exception e ) {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
         try
        {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;database=bios1;user=sa;password=fastrack3");
        }
        catch(Exception e)
        {
          System.out.println(e);
        }
        String sql = "select max(StudentId)+1 from StudentDetail";
        
        try{
            
            PreparedStatement pst = conn.prepareStatement(sql);
            rs =  pst.executeQuery();
            while(rs.next())
            {
                String sub = rs.getString(1);
                jTextField2.setText(sub);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox22ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        fillcombobox();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jComboBox11.removeAllItems();
        jComboBox22.removeAllItems();
        jComboBox33.removeAllItems();
        jComboBox44.removeAllItems();
        jComboBox55.removeAllItems();
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        l1.setText("subject1");
        l2.setText("subject2");
        l3.setText("subject3");
        l4.setText("subject4");
        l5.setText("subject5");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox jComboBox22;
    private javax.swing.JComboBox jComboBox33;
    private javax.swing.JComboBox jComboBox44;
    private javax.swing.JComboBox jComboBox55;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    // End of variables declaration//GEN-END:variables
}
