/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package erp;

import java.awt.Color;
import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class ViewEmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployeePage
     */
    public ViewEmployeePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.LIGHT_GRAY);
        DefaultTableModel model = null;
            model = new DefaultTableModel();
            jTable1.setModel(model);
            JTableHeader header = jTable1.getTableHeader();
            header.setOpaque(false);
            header.setBackground(Color.BLACK);
            model.addColumn("FIRSTNAME"); //1
            model.addColumn("SURNAME");//2
            model.addColumn("EMAIL");//3
            model.addColumn("DOB");//4
            model.addColumn("DEPT.");//14
            model.addColumn("GENDER");//5
            model.addColumn("DESIGNATION");//6
            model.addColumn("PHONE NO.");//7
            model.addColumn("ADDRESS"); //8
            model.addColumn("BS");// BS-BASIC SALARY //9
            model.addColumn("HRA");// HRA - HOUSE RENT ALLOWANCE //10
            model.addColumn("DA"); // DA- DEARNESS ALLOWANCE //11
            model.addColumn("SA"); // SA - SALARY ALLOWANCE //12
            model.addColumn("PF"); // PF- PROVIDENT FUND //13
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Employee");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(600, 325));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter Id/FirstName:");

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Find");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("View All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/images/2560x1440-black-solid-color-background.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addGap(66, 66, 66)
                        .addComponent(jButton3)))
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(27, 27, 27))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
                
 
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTextField1.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Please Enter Something");
        }
        else{
        try
        {
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;databaseName=bios1;user=sa;password=fastrack3");
          String a = "" ,b = "" , c = "" , d = "" , e = "", f = "" , g= "" , h= "" , i="";
            DefaultTableModel model = null;
            model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("FIRSTNAME"); //1
            model.addColumn("SURNAME");//2
            model.addColumn("EMAIL");//3
            model.addColumn("DOB");//4
            model.addColumn("DEPT.");//14
            model.addColumn("GENDER");//5
            model.addColumn("DESIGNATION");//6
            model.addColumn("PHONE NO.");//7
            model.addColumn("ADDRESS"); //8
            model.addColumn("BS");// BS-BASIC SALARY //9
            model.addColumn("HRA");// HRA - HOUSE RENT ALLOWANCE //10
            model.addColumn("DA"); // DA- DEARNESS ALLOWANCE //11
            model.addColumn("SA"); // SA - SALARY ALLOWANCE //12
            model.addColumn("PF"); // PF- PROVIDENT FUND //13
            String sql = "select * from EmployeeDetail where firstname like lower('" + jTextField1.getText() +"%') OR firstname like upper('" + jTextField1.getText() +"%')" ;
         
            PreparedStatement pst = con.prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            if(rs.next())
           {
            a = rs.getString(1);
            b = rs.getString(2);
            c = rs.getString(3);
            d = rs.getString(4);
            e = rs.getString(5);
            f = rs.getString(6);
            g = String.valueOf(rs.getString(7));
            h = rs.getString(8);
            i = String.valueOf(rs.getString(9));
           String j = String.valueOf(rs.getString(10));
           String k = String.valueOf(rs.getString(11));
           String l = String.valueOf(rs.getString(12));
           String m = String.valueOf(rs.getString(13));
           String n = String.valueOf(rs.getString(14));
           model.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j,k,l,m,n});
           String img = rs.getString("photo");
           ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH));
           jLabel2.setIcon(imageicon);
           } 
            else
                JOptionPane.showMessageDialog(null,"Data not found");
        } 
        catch(Exception e)
        {
            
        }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try
        {
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:51586;databaseName=bios1;user=sa;password=fastrack3");
          String a = "" ,b = "" , c = "" , d = "" , e = "", f = "" , g= "" , h= "" , i="";
            DefaultTableModel model = null;
            model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("FIRSTNAME"); //1
            model.addColumn("SURNAME");//2
            model.addColumn("EMAIL");//3
            model.addColumn("DOB");//4
            model.addColumn("DEPT.");//14
            model.addColumn("GENDER");//5
            model.addColumn("DESIGNATION");//6
            model.addColumn("PHONE NO.");//7
            model.addColumn("ADDRESS"); //8
            model.addColumn("BS");// BS-BASIC SALARY //9
            model.addColumn("HRA");// HRA - HOUSE RENT ALLOWANCE //10
            model.addColumn("DA"); // DA- DEARNESS ALLOWANCE //11
            model.addColumn("SA"); // SA - SALARY ALLOWANCE //12
            model.addColumn("PF"); // PF- PROVIDENT FUND //13
            String sql = "select * from EmployeeDetail " ;
         
            PreparedStatement pst = con.prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            while(rs.next())
           {
            a = rs.getString(1);
            b = rs.getString(2);
            c = rs.getString(3);
            d = rs.getString(4);
            e = rs.getString(5);
            f = rs.getString(6);
            g = String.valueOf(rs.getString(7));
            h = rs.getString(8);
            i = String.valueOf(rs.getString(9));
           String j = String.valueOf(rs.getString(10));
           String k = String.valueOf(rs.getString(11));
           String l = String.valueOf(rs.getString(12));
           String m = String.valueOf(rs.getString(13));
           String n = String.valueOf(rs.getString(14));
            model.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j,k,l,m,n});
           }
            
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
